package com.te6lim.ytcviewer

val raceIconResources = hashMapOf(
    Pair(RaceFilters.Aqua.query, R.drawable.aqua),
    Pair(RaceFilters.Beast.query, R.drawable.beast),
    Pair(RaceFilters.Beast_Warrior.query, R.drawable.beast_warrior),
    Pair(RaceFilters.Creator_God.query, R.drawable.divine),
    Pair(RaceFilters.Cyberse.query, R.drawable.machine),
    Pair(RaceFilters.Dinosaur.query, R.drawable.dinosaur),
    Pair(RaceFilters.Divine_Beast.query, R.drawable.divine_beast),
    Pair(RaceFilters.Dragon.query, R.drawable.dragon),
    Pair(RaceFilters.Fairy.query, R.drawable.fairy),
    Pair(RaceFilters.Fiend.query, R.drawable.fiend),
    Pair(RaceFilters.Fish.query, R.drawable.fish),
    Pair(RaceFilters.Insect.query, R.drawable.insect),
    Pair(RaceFilters.Machine.query, R.drawable.machine),
    Pair(RaceFilters.Plant.query, R.drawable.plant),
    Pair(RaceFilters.Psychic.query, R.drawable.psychic),
    Pair(RaceFilters.Pyro.query, R.drawable.pyro),
    Pair(RaceFilters.Reptile.query, R.drawable.reptile),
    Pair(RaceFilters.Rock.query, R.drawable.rock),
    Pair(RaceFilters.Sea_Serpent.query, R.drawable.sea_serpent),
    Pair(RaceFilters.Spellcaster.query, R.drawable.spellcaster),
    Pair(RaceFilters.Thunder.query, R.drawable.thunder),
    Pair(RaceFilters.Warrior.query, R.drawable.warrior),
    Pair(RaceFilters.Winged_Beast.query, R.drawable.winged_beast),
    Pair("Wyrm", R.drawable.dragon),
    Pair(SpellFilters.Normal.query, R.drawable.normal),
    Pair(SpellFilters.Field.query, R.drawable.field),
    Pair("Equip", R.drawable.equip),
    Pair(SpellFilters.Continuous.query, R.drawable.continuous),
    Pair(TrapFilters.Counter.query, R.drawable.counter),
    Pair(SpellFilters.Quick_Play.query, R.drawable.quick_play),
    Pair(SpellFilters.Ritual.query, R.drawable.ritual),
)

val attributeIconResources = hashMapOf(
    Pair(AttributeFilters.Dark.query, R.drawable.dark),
    Pair(AttributeFilters.Earth.query, R.drawable.earth),
    Pair(AttributeFilters.Fire.query, R.drawable.fire),
    Pair(AttributeFilters.Light.query, R.drawable.light),
    Pair(AttributeFilters.Water.query, R.drawable.water),
    Pair(AttributeFilters.Wind.query, R.drawable.wind),
    Pair(AttributeFilters.Divine.query, R.drawable.divine)
)